version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysqldb
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=kaddem
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    container_name: phpmyadmin
    env_file: ./.env
    ports:
     - 80
    environment:
     PMA_HOST: mysqldb

  springboot-be:
    depends_on:
      - mysqldb
    image: siwarbaccouche23/kaddem:0.0.1
    container_name: springboot-be
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql:/localhost:3306/kaddem/db?&createDatabaseIfNotExist=true",
            "spring.datasource.username" : "root",
            "spring.jpa.hibernate.ddl-auto": "update",
            "spring.datasource.password" : null,
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect"
          }'
    ports:
      - 8082:8082
    restart: on-failure

  volumes:
  db: