FROM openjdk:8-jdk-alpine
RUN apk --no-cache add curl
RUN curl -u admin:nexus -o kaddem.jar "http://192.168.2.136:8081/service/rest/v1/search/assets/download?sort=version&repository=maven-releases&maven.groupId=tn.esprit.spring&maven.artifactId=kaddem&maven.baseVersion=0.0.1&maven.extension=jar" -L
ENTRYPOINT ["java","-jar","/Kaddem.jar"]
EXPOSE 8082