version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
 phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    container_name: phpmyadmin
    env_file: ./.env
    ports:
      - "80:80"
    environment:
     PMA_HOST: mysqldb


 Springboot-app:
    depends_on:
      - mysqldb
    image: siwarbaccouche23/kaddem:latest
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
                 "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/kaddem/db?&createDatabaseIfNotExist=true",
                 "spring.datasource.username" : "root",
                 "spring.datasource.password" : null,
                 "spring.jpa.show-sql" : "true",
                 "spring.jpa.hibernate.ddl-auto" : "update",
                 "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
               }'
    ports:
      - "8089:8089"
    stdin_open: true
    tty: true


volumes:
  db:
